name: Compile LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          root_file: template.tex

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode -halt-on-error -shell-escape" template.tex
          mv template.pdf $GITHUB_WORKSPACE

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: template
          path: $GITHUB_WORKSPACE/template.pdf
